[2024-11-04T20:30:06.451+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T20:30:06.490+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag_v1.print_hello scheduled__2024-11-04T20:20:00+00:00 [queued]>
[2024-11-04T20:30:06.503+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag_v1.print_hello scheduled__2024-11-04T20:20:00+00:00 [queued]>
[2024-11-04T20:30:06.504+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-04T20:30:06.524+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): print_hello> on 2024-11-04 20:20:00+00:00
[2024-11-04T20:30:06.535+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag_v1', 'print_hello', 'scheduled__2024-11-04T20:20:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpiwc4gdhd']
[2024-11-04T20:30:06.533+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T20:30:06.542+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask print_hello
[2024-11-04T20:30:06.542+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2024-11-04T20:30:06.610+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag_v1.print_hello scheduled__2024-11-04T20:20:00+00:00 [running]> on host f3c6c1109f4c
[2024-11-04T20:30:06.758+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_dag_v1' AIRFLOW_CTX_TASK_ID='print_hello' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T20:20:00+00:00'
[2024-11-04T20:30:06.760+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T20:30:06.891+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-04T20:30:06.897+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello, World!"']
[2024-11-04T20:30:06.932+0000] {subprocess.py:86} INFO - Output:
[2024-11-04T20:30:06.959+0000] {subprocess.py:93} INFO - Hello, World!
[2024-11-04T20:30:06.960+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-04T20:30:07.014+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T20:30:07.015+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_dag_v1, task_id=print_hello, run_id=scheduled__2024-11-04T20:20:00+00:00, execution_date=20241104T202000, start_date=20241104T203006, end_date=20241104T203007
[2024-11-04T20:30:07.094+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-04T20:30:07.118+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T20:30:07.120+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
